WITH translations(slug, title) AS (
  VALUES
    ('accessories-fitnes', 'Аксессуары для фитнеса'),
    ('air', 'Надувное снаряжение'),
    ('air-sky', 'Надувное снаряжение для зимы'),
    ('backpack', 'Рюкзаки'),
    ('badminton', 'Бадминтон'),
    ('bag-sky', 'Лыжные сумки'),
    ('balance-board', 'Балансборды'),
    ('bandages', 'Бинты'),
    ('barbecue', 'Барбекю'),
    ('baseball', 'Бейсбол'),
    ('basketball', 'Баскетбол'),
    ('beach', 'Пляж'),
    ('bike-accessories', 'Велосипедные аксессуары'),
    ('binoculars', 'Бинокли'),
    ('bottle', 'Бутылки'),
    ('boxing-gloves', 'Боксерские перчатки'),
    ('buff', 'Баффы'),
    ('care', 'Уход'),
    ('chair', 'Стулья'),
    ('closes-ski', 'Лыжная одежда'),
    ('clothes-gloves', 'Перчатки'),
    ('dishes', 'Посуда'),
    ('down-jackets', 'Пуховики'),
    ('elasticbands', 'Фитнес-резинки'),
    ('extender', 'Эспандеры'),
    ('fasteners-sky', 'Лыжные крепления'),
    ('fin', 'Плавники'),
    ('fitness-gloves', 'Фитнес-перчатки'),
    ('fleece-jacket', 'Флисовые куртки'),
    ('flippers', 'Ласты'),
    ('food', 'Питание'),
    ('football', 'Футбол'),
    ('frisbee', 'Фрисби'),
    ('gas-burner', 'Газовые горелки'),
    ('gloves-sky', 'Лыжные перчатки'),
    ('goggles', 'Очки'),
    ('gymnastic', 'Гимнастика'),
    ('hammock', 'Гамаки'),
    ('hat', 'Шапки'),
    ('hat-sea', 'Головные уборы для воды'),
    ('helmet', 'Шлемы'),
    ('helmet-sky', 'Лыжные шлемы'),
    ('hermo', 'Термосы'),
    ('hermo2', 'Термокружки'),
    ('hoop', 'Обручи'),
    ('isotonic', 'Изотоники'),
    ('jumprope', 'Скакалки'),
    ('kettlebells', 'Гири'),
    ('kneepads', 'Наколенники'),
    ('knife', 'Ножи'),
    ('lantern', 'Фонари'),
    ('martialart-clothes', 'Одежда для единоборств'),
    ('martialart-exercise', 'Тренажеры для единоборств'),
    ('martialart-helmet', 'Шлемы для единоборств'),
    ('martialart-mma', 'MMA'),
    ('martialart-mouth-guard', 'Капы'),
    ('martialart-protection', 'Защита для единоборств'),
    ('martialart-rubber', 'Резина для единоборств'),
    ('martialart-shoes', 'Обувь для единоборств'),
    ('mask', 'Маски'),
    ('mat', 'Коврики'),
    ('mats', 'Маты'),
    ('medal', 'Медали'),
    ('mini', 'Мини'),
    ('oar', 'Весла'),
    ('padel', 'Падел'),
    ('pants', 'Брюки'),
    ('paws', 'Лапы'),
    ('protection', 'Защита'),
    ('roller', 'Ролики'),
    ('rope', 'Веревки'),
    ('rugby', 'Регби'),
    ('safety', 'Безопасность'),
    ('shaker', 'Шейкеры'),
    ('shoes', 'Обувь'),
    ('shoessea', 'Обувь для воды'),
    ('skigoggles', 'Горнолыжные очки'),
    ('sky-care', 'Уход за лыжами'),
    ('sleepingbag', 'Спальные мешки'),
    ('snowboardsky', 'Сноуборды и лыжи'),
    ('snowboardsky-boots', 'Ботинки для лыж и сноуборда'),
    ('snowshoes', 'Снегоступы'),
    ('socks', 'Носки'),
    ('socks-sky', 'Лыжные носки'),
    ('sunglasses', 'Солнцезащитные очки'),
    ('sunscreen', 'Солнцезащитные средства'),
    ('sup-accessories', 'Аксессуары для SUP'),
    ('supboard', 'SUP-доски'),
    ('technic', 'Техника'),
    ('tennis', 'Теннис'),
    ('tent', 'Палатки'),
    ('termoryukzak', 'Терморюкзаки'),
    ('thermalunderwear', 'Термобелье'),
    ('towel', 'Полотенца'),
    ('trekkingsticks', 'Треккинговые палки'),
    ('underwear', 'Белье'),
    ('vest', 'Жилеты'),
    ('volleyball', 'Волейбол'),
    ('windbreaker', 'Ветровки'),
    ('winter-chains', 'Зимние цепи')
)
UPDATE public.shop_categories AS c
SET title = t.title
FROM translations AS t
WHERE c.slug = t.slug;

WITH translations(slug, title) AS (
  VALUES
    ('aid', 'Аптечки'),
    ('armbands', 'Нарукавники'),
    ('axe', 'Топоры'),
    ('backpack', 'Рюкзаки'),
    ('badminton', 'Бадминтон'),
    ('badminton-accessories', 'Аксессуары для бадминтона'),
    ('bars', 'Брусья'),
    ('basketball', 'Баскетбол'),
    ('basketball-accessories', 'Аксессуары для баскетбола'),
    ('binoculars', 'Бинокли'),
    ('binoculars-accessories', 'Аксессуары для биноклей'),
    ('bracelet', 'Браслеты'),
    ('burner', 'Горелки'),
    ('cap', 'Кепки'),
    ('chair', 'Стулья'),
    ('coffe', 'Кофе'),
    ('compass', 'Компасы'),
    ('cup', 'Чашки'),
    ('cutlery', 'Столовые приборы'),
    ('elbowpads', 'Налокотники'),
    ('fannypack', 'Поясные сумки'),
    ('football', 'Футбол'),
    ('football-accessories', 'Аксессуары для футбола'),
    ('gas-burner', 'Газовые горелки'),
    ('gas-burner-accessories', 'Аксессуары для газовых горелок'),
    ('gymbag', 'Спортивные сумки'),
    ('headlamp', 'Налобные фонари'),
    ('hermo', 'Термосы'),
    ('inflatable', 'Надувное снаряжение'),
    ('izy', 'Изи'),
    ('jackets-ski', 'Лыжные куртки'),
    ('kneepads', 'Наколенники'),
    ('knife', 'Ножи'),
    ('knife-accessories', 'Аксессуары для ножей'),
    ('lamps', 'Лампы'),
    ('lazy', 'Лежаки'),
    ('mat', 'Коврики'),
    ('mat-accessories', 'Аксессуары для ковриков'),
    ('mattress', 'Матрасы'),
    ('mini', 'Мини'),
    ('mini-accessories', 'Аксессуары Mini'),
    ('monocular', 'Монокуляры'),
    ('mug', 'Кружки'),
    ('padel', 'Падел'),
    ('padel-accessories', 'Аксессуары для падела'),
    ('pants-ski', 'Лыжные брюки'),
    ('pillows', 'Подушки'),
    ('plate', 'Тарелки'),
    ('pliers', 'Плоскогубцы'),
    ('pool', 'Бассейны'),
    ('pot', 'Котелки'),
    ('pump', 'Насосы'),
    ('raincoat', 'Дождевики'),
    ('repellent', 'Репелленты'),
    ('repeller', 'Отпугиватели'),
    ('roller', 'Ролики'),
    ('roller-accessories', 'Аксессуары для роликов'),
    ('roller-bags', 'Сумки для роликов'),
    ('sandals', 'Сандалии'),
    ('saw', 'Пилы'),
    ('seats', 'Сиденья'),
    ('self-inflating', 'Самонадувающиеся'),
    ('set-ski', 'Лыжные комплекты'),
    ('setdishes', 'Наборы посуды'),
    ('shoes-accessories', 'Аксессуары для обуви'),
    ('shoes-covers', 'Бахилы'),
    ('shovel', 'Лопаты'),
    ('sleepingbag', 'Спальные мешки'),
    ('sunglasses', 'Солнцезащитные очки'),
    ('sunglasses-accessories', 'Аксессуары для очков'),
    ('tables', 'Столы'),
    ('teapot', 'Чайники'),
    ('technic', 'Техника'),
    ('tennis', 'Теннис'),
    ('tennis-accessories', 'Аксессуары для тенниса'),
    ('tent', 'Палатки'),
    ('tent-accessories', 'Аксессуары для палаток'),
    ('termoryukzak', 'Терморюкзаки'),
    ('thermalblanket', 'Термоодеяла'),
    ('thermos', 'Термосы'),
    ('trekking-shoes', 'Треккинговая обувь'),
    ('trekkingsticks', 'Треккинговые палки'),
    ('trekkingsticks-accessories', 'Аксессуары для треккинговых палок'),
    ('vest', 'Жилеты'),
    ('warmhat', 'Теплые шапки'),
    ('watch', 'Часы'),
    ('waterprouf', 'Водонепроницаемые товары')
)
UPDATE public.shop_subcategories AS s
SET title = t.title
FROM translations AS t
WHERE s.slug = t.slug;