export const RENT_SKY = [
  {
    order: true,
    id: 1009000029,
    titleEng: "",
    title: "Сертификат на продажу снаряжения",
    img: "sale3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 100,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 1009000029,
    titleEng: "",
    title: "Сертификат на продажу снаряжения",
    img: "sale3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 200,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 1009000029,
    titleEng: "",
    title: "Сертификат на продажу снаряжения",
    img: "sale3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 500,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 1009000029,
    titleEng: "",
    title: "Сертификат на продажу снаряжения",
    img: "sale3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 1000,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 1009000029,
    titleEng: "",
    title: "Сертификат на продажу снаряжения",
    img: "sale3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 1500,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 1009000029,
    titleEng: "",
    title: "Сертификат на продажу снаряжения",
    img: "sale3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 2000,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 1009000029,
    titleEng: "",
    title: "Сертификат на продажу снаряжения",
    img: "sale3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 3000,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 1009000029,
    titleEng: "",
    title: "Сертификат на продажу снаряжения",
    img: "sale3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 4000,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 1009000029,
    titleEng: "",
    title: "Сертификат на продажу снаряжения",
    img: "sale3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 5000,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 21009000029,
    titleEng: "",
    title: "Сертификат на аренду снаряжения",
    img: "rent3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 100,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 21009000029,
    titleEng: "",
    title: "Сертификат на аренду снаряжения",
    img: "rent3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 200,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 21009000029,
    titleEng: "",
    title: "Сертификат на аренду снаряжения",
    img: "rent3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 500,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 21009000029,
    titleEng: "",
    title: "Сертификат на аренду снаряжения",
    img: "rent3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 1000,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 21009000029,
    titleEng: "",
    title: "Сертификат на аренду снаряжения",
    img: "rent3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 1500,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
  {
    order: true,
    id: 21009000029,
    titleEng: "",
    title: "Сертификат на аренду снаряжения",
    img: "rent3.webp",
    descEng: "",
    desc: "номиналом от 100 до 5000 лари.",
    category: "tent",
    price: 2000,
    shortlyEng: "",
    shortly: "",
    column: [
      "В комментариях к заказу, пожалуйста, укажите, какой номинал вам необходим.",
    ],
    columnEng: [],
  },
];
