const SALE = [
  {
    id: 1989804,
    titleEng: "",
    title: "ПАЛАТКА Naturehike Cloud UP 1 210T",
    img: "1-cloudup1-green-210T.jpg",
    descEng: "1-person, double-layer 120*295*110",
    desc: "1 местная двухслойная 180*300*110",
    category: "tent",
    order: true,
    oldPrice: 390,
    newPrice: 242,

    shortlyEng: "Ultralight backpacking tent with a skirt.",
    shortly:
      "Ультралегкая одноместная палатка Naturehike Cloud UP1 для пеших, водных и вело-походов. Полный вес 1,57 кг. Легкий вес, компактность в сложенном виде и просторность в разложенном - отличный выбор независимого одиночки.",
    column: [
      "Количество мест: 1",
      "Размер спального места	230 x 110",
      "Водостойкость навес (мм в. ст.): >3000",
      "Водостойкость дна (мм в. ст.): >3000",
      "Материал каркаса: Анодированный алюминий 7001",
      "Размер в сложенном виде (см): 40х12",
      "Материал тента: Полиэстер 210T",
      "Материал дна: 150D Оксфорд",
      "Полный вес 1,57 кг. ",
    ],
    columnEng: [],
  },
  {
    id: 12001,
    title: "ПАЛАТКА NATUREHIKE CLOUD UP 2 210T",
    titleEng: "TENT NATUREHIKE CLOUD UP 2 210T",
    img: "cloudup2-green-210T.jpg",
    desc: "2-х местная двухслойная 150*275*110",
    descEng: "2-person, double-layer 150*275*110",
    category: "tent",
    price: 440,
    oldPrice: 440,
    newPrice: 286,
    order: true,
    shortlyEng:
      "Ultralight two-person tent for hiking, water, and biking trips. The spacious vestibule can accommodate a couple of large-sized backpacks.",
    shortly:
      "Ультралегкая двухместная палатка для пеших, водных и вело-походов. В просторный тамбур можно разместить пару рюкзаков внушительных размеров.",
    column: [
      "Каркас изготовлен из очень прочного, но гибкого легированного алюминия марки 7001",
      "Комната 210*125 см",
      "Высота: 100 см",
      "Внешний тент выполнен из тонкого и легкого полиэстера 210T с плетением RipStop и PU пропиткой",
      "Ткань устойчива к ультрафиолету, не растягивается при намокании",
      "В комплект входит дополнительный пол (футпринт), защищающий дно палатки от повреждений и загрязнения",
      "Вес: 1,83 кг",
      "Палатка комплектуется фирменными колышками Y-образного сечения. Вес одного всего 9 грамм. На каждом из них предусмотрены выемки для фиксации оттяжки и петелька из шнура для извлечения из грунта",
      "Водостойкость навес (мм в. ст.): >3000",
      "Водостойкость дна (мм в. ст.): >4000",
      "Чехол для хранения и транспортировки",
    ],
    columnEng: [
      "The frame is made of very durable but flexible alloy aluminum grade 7001.",
      "Room size: 210*125 cm.",
      "Height: 100 cm.",
      "The outer tent is made of thin and lightweight 210T polyester with RipStop weave and PU coating.",
      "The fabric is resistant to ultraviolet rays and does not stretch when wet.",
      "The kit includes an additional groundsheet (footprint) to protect the tent floor from damage and dirt.",
      "Weight: 1.83 kg.",
      "The tent comes with branded Y-shaped section stakes. Each stake weighs only 9 grams. They have notches for attaching guy lines and cord loops for extraction from the ground.",
      "Rainfly waterproof rating (mm H2O): >3000.",
      "Floor waterproof rating (mm H2O): >3000.",
      "Storage and transport bag.",
    ],
  },
  {
    id: 19804,
    titleEng: "TENT NATUREHIKE CLOUD UP 3 20D SNOW SKIRT",
    title: "ПАЛАТКА NATUREHIKE CLOUD UP 3 20D",
    img: "20DGREYWITHSKIRT.webp",
    descEng: "3-person, double-layer 180*300*110",
    desc: "3-х местная двухслойная 180*300*110",
    category: "tent",
    order: true,
    price: 580,
    oldPrice: 580,
    newPrice: 396,
    shortlyEng: "Ultralight backpacking tent with a skirt.",
    shortly: "Ультралёгкая туристическая палатка с юбкой.",
    column: [
      "Cо снежной юбкой",
      "Тент изготовлен из силиконизированного нейлона 20D",
      "Комната 215*180 см",
      "Высота: 110 см",
      "Юбка по краю тента защитит от снега, дождя и сильного ветра",
      "Основная часть внутренней палатки, выполненная из сетки B3, защищает от насекомых и обеспечивает циркуляцию воздуха",
      "Ткань устойчива к ультрафиолету, не растягивается при намокании",
      "В комплект входит дополнительный пол (футпринт), защищающий дно палатки от повреждений и загрязнения",
      "Вес: 2,05 кг",
      "Палатка комплектуется фирменными колышками Y-образного сечения. Вес одного всего 9 грамм. На каждом из них предусмотрены выемки для фиксации оттяжки и петелька из шнура для извлечения из грунта",
      "Водостойкость навес (мм в. ст.): > 4000",
      "Водостойкость дна (мм в. ст.): > 4000",
      "Чехол для хранения и транспортировки",
    ],
    columnEng: [
      "The tent is made of silicone-coated nylon 20D.",
      "Room size: 215*180 cm.",
      "Height: 110 cm.",
      "The skirt along the edge of the tent will protect from snow, rain, and strong winds.",
      "The main part of the inner tent, made of B3 mesh, protects against insects and provides air circulation.",
      "The fabric is resistant to ultraviolet rays and does not stretch when wet.",
      "The kit includes an additional groundsheet (footprint) to protect the tent floor from damage and dirt.",
      "Weight: 2.05 kg.",
      "The tent comes with branded Y-shaped section stakes. Each stake weighs only 9 grams. They have notches for attaching guy lines and cord loops for extraction from the ground.",
      "Rainfly waterproof rating (mm H2O): >4000.",
      "Floor waterproof rating (mm H2O): >4000.",
      "Storage and transport bag.",
    ],
  },
  {
    order: true,
    id: 15400013,
    titleEng: "",
    title: "Палатка-туалет-душ Naturehike Foldable Portable ",
    img: "47abb5b625f46a6b26179ce3e5387be4.jpg",
    descEng: "",
    desc: "коричневый/серебренный",
    category: "tent",
    price: 190,
    oldPrice: 190,
    newPrice: 99,
    column: [
      "Naturehike Foldable Changing Tent — лёгкая и удобная палатка для душа, туалета и переодевания",
      "Быстрая установка, компактна при транспортировке — вес 2.67 кг",
      "Однослойная конструкция, подходит для весны, лета и осени",
      "Материал тента: прочный полиэстер Оксфорд 210T",
      "Сетчатое окно — отличная вентиляция внутри",
      "Крючок в верхней части для подвешивания душа или одежды",
      "Внутренний карман из сетки — для хранения мыла и мелочей",
      "Надёжная защита от солнца и ветра",
      "Размер в разложенном виде: 115×115×190 см",
      "Размер в упаковке: всего 55×6 см — удобно брать с собой",
      "Идеальна для кемпинга, треккинга, пляжа и фестивалей",
    ],
    columnEng: [],
  },
  {
    id: 154000134,
    title: "Стойки для тента Naturehike Aluminum",
    img: "533c4e39-8a46-4c25-8f5e-50170752ca70_1200x1200.webp",
    order: true,
    desc: "2.4meters 28MM",
    category: "accessories",
    price: 88,
    oldPrice: 88,
    newPrice: 44,
    column: [
      "Алюминиевые стойки для палатки Naturehike — надёжная опора в походах и кемпинге",
      "Длина: 2.4 м, конструкция из 4 секций — регулируется по высоте",
      "Лёгкие и прочные — выполнены из алюминиевого сплава",
      "Надёжная застёжка-липучка (крюк и петля) для фиксации",
      "Идеальны для установки тента, навеса или дополнительной опоры",
      "Элегантный чёрный дизайн — сочетается с любой палаткой",
      "Материалы: алюминиевый сплав, ткань — полиэстер",
      "Вес легко распределяется — подходит для рюкзачного туризма",
      "Уровень водонепроницаемости: не водонепроницаемый",
    ],
  },
  {
    id: 1554000134,
    title: "Стойки для тента Naturehike Aluminum",
    img: "ca57ee1e-5ec3-4273-ba33-ba58d8906b71_1200x1200.webp",
    order: true,
    desc: "Wood 2.8meter 33MM",
    category: "accessories",
    price: 99,
    oldPrice: 99,
    newPrice: 60,
    column: [
      "Алюминиевые стойки для палатки Naturehike — надёжная опора в походах и кемпинге",
      "Длина: 2.8 м, конструкция из 4 секций — регулируется по высоте",
      "Лёгкие и прочные — выполнены из алюминиевого сплава",
      "Надёжная застёжка-липучка (крюк и петля) для фиксации",
      "Идеальны для установки тента, навеса или дополнительной опоры",
      "Элегантный дизайн — сочетается с любой палаткой",
      "Материалы: алюминиевый сплав, ткань — полиэстер",
      "Вес легко распределяется — подходит для рюкзачного туризма",
      "Уровень водонепроницаемости: не водонепроницаемый",
    ],
  },
  {
    id: 190014901,
    title: "Спальный мешок Naturehike M320",
    titleEng: "",
    img: "9022165.970.webp",
    descEng: "",
    desc: "(левый), зеленый камуфляж",
    category: "sleepingbag",
    price: 140,
    order: true,
    oldPrice: 140,
    newPrice: 75,
    columnEng: [""],
    column: [
      " Спальник Naturehike с капюшоном и мягкой подкладкой",
      "Водоотталкивающая тафта с внутренним покрытием под вельвет (100 г/м²)",
      "Наполнитель — Hollow Fiber, сохраняет тепло при 15°C",
      "Размер: 190+30 × 80 см, вес: 1.56 кг, удобный чехол в комплекте",
      "Идеален для весны, лета и осени, температурный диапазон до +1°C",
    ],
  },
  {
    id: 1900149002,
    title: "Спальный мешок Naturehike M320",
    titleEng: "",
    img: "9022165.970.webp",
    descEng: "",
    desc: "(правый), зеленый камуфляж",
    category: "sleepingbag",
    price: 140,
    oldPrice: 140,
    newPrice: 75,
    order: true,
    columnEng: [""],
    column: [
      " Спальник Naturehike с капюшоном и мягкой подкладкой",
      "Водоотталкивающая тафта с внутренним покрытием под вельвет (100 г/м²)",
      "Наполнитель — Hollow Fiber, сохраняет тепло при 15°C",
      "Размер: 190+30 × 80 см, вес: 1.56 кг, удобный чехол в комплекте",
      "Идеален для весны, лета и осени, температурный диапазон до +1°C",
    ],
  },
];
