/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as RockClimbingRouteImport } from './routes/rockClimbing'
import { Route as RentRouteImport } from './routes/rent'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HikesIndexRouteImport } from './routes/hikes.index'
import { Route as SaleSearchRouteImport } from './routes/sale.search'
import { Route as SaleSaleRouteImport } from './routes/sale.sale'
import { Route as SaleGroupRouteImport } from './routes/sale.$group'
import { Route as RentSaleRouteImport } from './routes/rent.sale'
import { Route as RentGroupRouteImport } from './routes/rent.$group'
import { Route as HikesSlugRouteImport } from './routes/hikes.$slug'
import { Route as AppSlugRouteImport } from './routes/app.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as SaleGroupCategoryRouteImport } from './routes/sale.$group.$category'
import { Route as RentGroupCategoryRouteImport } from './routes/rent.$group.$category'
import { Route as SaleGroupCategorySubcategoryRouteImport } from './routes/sale.$group.$category.$subcategory'
import { Route as RentGroupCategorySubcategoryRouteImport } from './routes/rent.$group.$category.$subcategory'
import { Route as AdminAdminTTableRouteImport } from './routes/_admin/admin.t.$table'

const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const RockClimbingRoute = RockClimbingRouteImport.update({
  id: '/rockClimbing',
  path: '/rockClimbing',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HikesIndexRoute = HikesIndexRouteImport.update({
  id: '/hikes/',
  path: '/hikes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleSearchRoute = SaleSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SaleRoute,
} as any)
const SaleSaleRoute = SaleSaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => SaleRoute,
} as any)
const SaleGroupRoute = SaleGroupRouteImport.update({
  id: '/$group',
  path: '/$group',
  getParentRoute: () => SaleRoute,
} as any)
const RentSaleRoute = RentSaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => RentRoute,
} as any)
const RentGroupRoute = RentGroupRouteImport.update({
  id: '/$group',
  path: '/$group',
  getParentRoute: () => RentRoute,
} as any)
const HikesSlugRoute = HikesSlugRouteImport.update({
  id: '/hikes/$slug',
  path: '/hikes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugRoute = AppSlugRouteImport.update({
  id: '/app/$slug',
  path: '/app/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const SaleGroupCategoryRoute = SaleGroupCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => SaleGroupRoute,
} as any)
const RentGroupCategoryRoute = RentGroupCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => RentGroupRoute,
} as any)
const SaleGroupCategorySubcategoryRoute =
  SaleGroupCategorySubcategoryRouteImport.update({
    id: '/$subcategory',
    path: '/$subcategory',
    getParentRoute: () => SaleGroupCategoryRoute,
  } as any)
const RentGroupCategorySubcategoryRoute =
  RentGroupCategorySubcategoryRouteImport.update({
    id: '/$subcategory',
    path: '/$subcategory',
    getParentRoute: () => RentGroupCategoryRoute,
  } as any)
const AdminAdminTTableRoute = AdminAdminTTableRouteImport.update({
  id: '/admin/t/$table',
  path: '/admin/t/$table',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/rent': typeof RentRouteWithChildren
  '/rockClimbing': typeof RockClimbingRoute
  '/sale': typeof SaleRouteWithChildren
  '/search': typeof SearchRoute
  '/service': typeof ServiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/$slug': typeof AppSlugRoute
  '/hikes/$slug': typeof HikesSlugRoute
  '/rent/$group': typeof RentGroupRouteWithChildren
  '/rent/sale': typeof RentSaleRoute
  '/sale/$group': typeof SaleGroupRouteWithChildren
  '/sale/sale': typeof SaleSaleRoute
  '/sale/search': typeof SaleSearchRoute
  '/hikes/': typeof HikesIndexRoute
  '/rent/$group/$category': typeof RentGroupCategoryRouteWithChildren
  '/sale/$group/$category': typeof SaleGroupCategoryRouteWithChildren
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/t/$table': typeof AdminAdminTTableRoute
  '/rent/$group/$category/$subcategory': typeof RentGroupCategorySubcategoryRoute
  '/sale/$group/$category/$subcategory': typeof SaleGroupCategorySubcategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/rent': typeof RentRouteWithChildren
  '/rockClimbing': typeof RockClimbingRoute
  '/sale': typeof SaleRouteWithChildren
  '/search': typeof SearchRoute
  '/service': typeof ServiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/$slug': typeof AppSlugRoute
  '/hikes/$slug': typeof HikesSlugRoute
  '/rent/$group': typeof RentGroupRouteWithChildren
  '/rent/sale': typeof RentSaleRoute
  '/sale/$group': typeof SaleGroupRouteWithChildren
  '/sale/sale': typeof SaleSaleRoute
  '/sale/search': typeof SaleSearchRoute
  '/hikes': typeof HikesIndexRoute
  '/rent/$group/$category': typeof RentGroupCategoryRouteWithChildren
  '/sale/$group/$category': typeof SaleGroupCategoryRouteWithChildren
  '/admin': typeof AdminAdminIndexRoute
  '/admin/t/$table': typeof AdminAdminTTableRoute
  '/rent/$group/$category/$subcategory': typeof RentGroupCategorySubcategoryRoute
  '/sale/$group/$category/$subcategory': typeof SaleGroupCategorySubcategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/rent': typeof RentRouteWithChildren
  '/rockClimbing': typeof RockClimbingRoute
  '/sale': typeof SaleRouteWithChildren
  '/search': typeof SearchRoute
  '/service': typeof ServiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/$slug': typeof AppSlugRoute
  '/hikes/$slug': typeof HikesSlugRoute
  '/rent/$group': typeof RentGroupRouteWithChildren
  '/rent/sale': typeof RentSaleRoute
  '/sale/$group': typeof SaleGroupRouteWithChildren
  '/sale/sale': typeof SaleSaleRoute
  '/sale/search': typeof SaleSearchRoute
  '/hikes/': typeof HikesIndexRoute
  '/rent/$group/$category': typeof RentGroupCategoryRouteWithChildren
  '/sale/$group/$category': typeof SaleGroupCategoryRouteWithChildren
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/t/$table': typeof AdminAdminTTableRoute
  '/rent/$group/$category/$subcategory': typeof RentGroupCategorySubcategoryRoute
  '/sale/$group/$category/$subcategory': typeof SaleGroupCategorySubcategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/contact'
    | '/rent'
    | '/rockClimbing'
    | '/sale'
    | '/search'
    | '/service'
    | '/admin/login'
    | '/app/$slug'
    | '/hikes/$slug'
    | '/rent/$group'
    | '/rent/sale'
    | '/sale/$group'
    | '/sale/sale'
    | '/sale/search'
    | '/hikes/'
    | '/rent/$group/$category'
    | '/sale/$group/$category'
    | '/admin/'
    | '/admin/t/$table'
    | '/rent/$group/$category/$subcategory'
    | '/sale/$group/$category/$subcategory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/contact'
    | '/rent'
    | '/rockClimbing'
    | '/sale'
    | '/search'
    | '/service'
    | '/admin/login'
    | '/app/$slug'
    | '/hikes/$slug'
    | '/rent/$group'
    | '/rent/sale'
    | '/sale/$group'
    | '/sale/sale'
    | '/sale/search'
    | '/hikes'
    | '/rent/$group/$category'
    | '/sale/$group/$category'
    | '/admin'
    | '/admin/t/$table'
    | '/rent/$group/$category/$subcategory'
    | '/sale/$group/$category/$subcategory'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/checkout'
    | '/contact'
    | '/rent'
    | '/rockClimbing'
    | '/sale'
    | '/search'
    | '/service'
    | '/admin/login'
    | '/app/$slug'
    | '/hikes/$slug'
    | '/rent/$group'
    | '/rent/sale'
    | '/sale/$group'
    | '/sale/sale'
    | '/sale/search'
    | '/hikes/'
    | '/rent/$group/$category'
    | '/sale/$group/$category'
    | '/_admin/admin/'
    | '/_admin/admin/t/$table'
    | '/rent/$group/$category/$subcategory'
    | '/sale/$group/$category/$subcategory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  RentRoute: typeof RentRouteWithChildren
  RockClimbingRoute: typeof RockClimbingRoute
  SaleRoute: typeof SaleRouteWithChildren
  SearchRoute: typeof SearchRoute
  ServiceRoute: typeof ServiceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AppSlugRoute: typeof AppSlugRoute
  HikesSlugRoute: typeof HikesSlugRoute
  HikesIndexRoute: typeof HikesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rockClimbing': {
      id: '/rockClimbing'
      path: '/rockClimbing'
      fullPath: '/rockClimbing'
      preLoaderRoute: typeof RockClimbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hikes/': {
      id: '/hikes/'
      path: '/hikes'
      fullPath: '/hikes/'
      preLoaderRoute: typeof HikesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/search': {
      id: '/sale/search'
      path: '/search'
      fullPath: '/sale/search'
      preLoaderRoute: typeof SaleSearchRouteImport
      parentRoute: typeof SaleRoute
    }
    '/sale/sale': {
      id: '/sale/sale'
      path: '/sale'
      fullPath: '/sale/sale'
      preLoaderRoute: typeof SaleSaleRouteImport
      parentRoute: typeof SaleRoute
    }
    '/sale/$group': {
      id: '/sale/$group'
      path: '/$group'
      fullPath: '/sale/$group'
      preLoaderRoute: typeof SaleGroupRouteImport
      parentRoute: typeof SaleRoute
    }
    '/rent/sale': {
      id: '/rent/sale'
      path: '/sale'
      fullPath: '/rent/sale'
      preLoaderRoute: typeof RentSaleRouteImport
      parentRoute: typeof RentRoute
    }
    '/rent/$group': {
      id: '/rent/$group'
      path: '/$group'
      fullPath: '/rent/$group'
      preLoaderRoute: typeof RentGroupRouteImport
      parentRoute: typeof RentRoute
    }
    '/hikes/$slug': {
      id: '/hikes/$slug'
      path: '/hikes/$slug'
      fullPath: '/hikes/$slug'
      preLoaderRoute: typeof HikesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug': {
      id: '/app/$slug'
      path: '/app/$slug'
      fullPath: '/app/$slug'
      preLoaderRoute: typeof AppSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sale/$group/$category': {
      id: '/sale/$group/$category'
      path: '/$category'
      fullPath: '/sale/$group/$category'
      preLoaderRoute: typeof SaleGroupCategoryRouteImport
      parentRoute: typeof SaleGroupRoute
    }
    '/rent/$group/$category': {
      id: '/rent/$group/$category'
      path: '/$category'
      fullPath: '/rent/$group/$category'
      preLoaderRoute: typeof RentGroupCategoryRouteImport
      parentRoute: typeof RentGroupRoute
    }
    '/sale/$group/$category/$subcategory': {
      id: '/sale/$group/$category/$subcategory'
      path: '/$subcategory'
      fullPath: '/sale/$group/$category/$subcategory'
      preLoaderRoute: typeof SaleGroupCategorySubcategoryRouteImport
      parentRoute: typeof SaleGroupCategoryRoute
    }
    '/rent/$group/$category/$subcategory': {
      id: '/rent/$group/$category/$subcategory'
      path: '/$subcategory'
      fullPath: '/rent/$group/$category/$subcategory'
      preLoaderRoute: typeof RentGroupCategorySubcategoryRouteImport
      parentRoute: typeof RentGroupCategoryRoute
    }
    '/_admin/admin/t/$table': {
      id: '/_admin/admin/t/$table'
      path: '/admin/t/$table'
      fullPath: '/admin/t/$table'
      preLoaderRoute: typeof AdminAdminTTableRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminTTableRoute: typeof AdminAdminTTableRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminTTableRoute: AdminAdminTTableRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RentGroupCategoryRouteChildren {
  RentGroupCategorySubcategoryRoute: typeof RentGroupCategorySubcategoryRoute
}

const RentGroupCategoryRouteChildren: RentGroupCategoryRouteChildren = {
  RentGroupCategorySubcategoryRoute: RentGroupCategorySubcategoryRoute,
}

const RentGroupCategoryRouteWithChildren =
  RentGroupCategoryRoute._addFileChildren(RentGroupCategoryRouteChildren)

interface RentGroupRouteChildren {
  RentGroupCategoryRoute: typeof RentGroupCategoryRouteWithChildren
}

const RentGroupRouteChildren: RentGroupRouteChildren = {
  RentGroupCategoryRoute: RentGroupCategoryRouteWithChildren,
}

const RentGroupRouteWithChildren = RentGroupRoute._addFileChildren(
  RentGroupRouteChildren,
)

interface RentRouteChildren {
  RentGroupRoute: typeof RentGroupRouteWithChildren
  RentSaleRoute: typeof RentSaleRoute
}

const RentRouteChildren: RentRouteChildren = {
  RentGroupRoute: RentGroupRouteWithChildren,
  RentSaleRoute: RentSaleRoute,
}

const RentRouteWithChildren = RentRoute._addFileChildren(RentRouteChildren)

interface SaleGroupCategoryRouteChildren {
  SaleGroupCategorySubcategoryRoute: typeof SaleGroupCategorySubcategoryRoute
}

const SaleGroupCategoryRouteChildren: SaleGroupCategoryRouteChildren = {
  SaleGroupCategorySubcategoryRoute: SaleGroupCategorySubcategoryRoute,
}

const SaleGroupCategoryRouteWithChildren =
  SaleGroupCategoryRoute._addFileChildren(SaleGroupCategoryRouteChildren)

interface SaleGroupRouteChildren {
  SaleGroupCategoryRoute: typeof SaleGroupCategoryRouteWithChildren
}

const SaleGroupRouteChildren: SaleGroupRouteChildren = {
  SaleGroupCategoryRoute: SaleGroupCategoryRouteWithChildren,
}

const SaleGroupRouteWithChildren = SaleGroupRoute._addFileChildren(
  SaleGroupRouteChildren,
)

interface SaleRouteChildren {
  SaleGroupRoute: typeof SaleGroupRouteWithChildren
  SaleSaleRoute: typeof SaleSaleRoute
  SaleSearchRoute: typeof SaleSearchRoute
}

const SaleRouteChildren: SaleRouteChildren = {
  SaleGroupRoute: SaleGroupRouteWithChildren,
  SaleSaleRoute: SaleSaleRoute,
  SaleSearchRoute: SaleSearchRoute,
}

const SaleRouteWithChildren = SaleRoute._addFileChildren(SaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  RentRoute: RentRouteWithChildren,
  RockClimbingRoute: RockClimbingRoute,
  SaleRoute: SaleRouteWithChildren,
  SearchRoute: SearchRoute,
  ServiceRoute: ServiceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AppSlugRoute: AppSlugRoute,
  HikesSlugRoute: HikesSlugRoute,
  HikesIndexRoute: HikesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
