// Curated complementary categories per shop category slug.
// Order matters: earlier entries are higher priority.
// Used by getShopProductBySlug to build "С этим товаром покупают".
export const SHOP_COMPLEMENT_MAP: Record<string, string[]> = {
  // Cycling / Roller
  roller: ["protection", "helmet", "kneePads", "fitness_gloves", "sunglasses", "socks"],
  protection: ["helmet", "roller", "kneePads", "fitness_gloves", "sunglasses"],
  helmet: ["protection", "roller", "kneePads", "sunglasses", "fitness_gloves"],
  bike_accessories: ["helmet", "protection", "sunglasses", "bottle", "backpack"],

  // Tourism / Camping
  tent: ["sleepingbag", "mat", "lantern", "gas_burner", "chair", "knife", "raincoat"],
  sleepingbag: ["tent", "mat", "termoryukzak", "lantern", "thermalUnderwear"],
  mat: ["tent", "sleepingbag", "lantern", "hammock"],
  backpack: ["bottle", "termoryukzak", "raincoat", "lantern", "rope", "sunglasses", "knife"],
  trekkingsticks: ["backpack", "shoes", "bottle", "sunglasses", "hat"],
  hermo: ["backpack", "trekkingsticks", "tent", "sunglasses"],
  raincoat: ["backpack", "trekkingsticks", "tent", "sunglasses"],
  gas_burner: ["dishes", "tent", "termoryukzak", "knife", "food"],
  lantern: ["tent", "sleepingbag", "knife", "backpack"],
  sunglasses: ["hat", "buff", "backpack", "trekkingsticks"],
  termoryukzak: ["bottle", "food", "dishes", "backpack"],
  bottle: ["backpack", "termoryukzak", "isotonic", "trekkingsticks"],
  dishes: ["gas_burner", "tent", "knife", "food"],
  barbecue: ["knife", "dishes", "food", "chair"],
  knife: ["backpack", "tent", "lantern", "rope"],
  binoculars: ["backpack", "sunglasses", "hat"],
  chair: ["tent", "hammock", "barbecue", "lantern"],
  hammock: ["mat", "rope", "chair", "lantern"],
  rope: ["knife", "backpack", "safety", "trekkingsticks"],
  air: ["mat", "tent", "sleepingbag"],
  safety: ["helmet", "rope", "lantern", "backpack"],
  technic: ["lantern", "backpack", "binoculars"],
  food: ["isotonic", "bottle", "termoryukzak", "dishes"],

  // Clothes / Shoes
  windbreaker: ["pants", "shoes", "buff", "hat", "fleece_jacket", "backpack"],
  fleece_jacket: ["windbreaker", "thermalUnderwear", "pants", "hat", "buff"],
  down_jackets: ["thermalUnderwear", "hat", "clothes_gloves", "pants", "buff"],
  pants: ["windbreaker", "shoes", "socks", "fleece_jacket", "thermalUnderwear"],
  shoes: ["socks", "pants", "care", "trekkingsticks"],
  buff: ["hat", "windbreaker", "sunglasses", "fleece_jacket"],
  clothes_gloves: ["hat", "buff", "thermalUnderwear", "down_jackets"],
  hat: ["buff", "windbreaker", "clothes_gloves", "fleece_jacket"],
  care: ["shoes", "pants", "windbreaker"],
  thermalUnderwear: ["socks", "fleece_jacket", "hat", "clothes_gloves", "pants"],
  socks: ["shoes", "pants", "thermalUnderwear"],
  underwear: ["thermalUnderwear", "socks", "pants"],

  // Martial arts
  boxing_gloves: ["bandages", "martialart_mouth_guard", "martialart_helmet", "martialart_protection", "paws"],
  martialart_helmet: ["boxing_gloves", "martialart_protection", "martialart_mouth_guard", "bandages"],
  martialart_mouth_guard: ["boxing_gloves", "martialart_helmet", "bandages"],
  martialart_protection: ["boxing_gloves", "martialart_helmet", "bandages", "martialart_mouth_guard"],
  paws: ["boxing_gloves", "bandages", "martialart_protection"],
  bandages: ["boxing_gloves", "martialart_mouth_guard", "martialart_protection"],
  martialart_clothes: ["martialart_shoes", "boxing_gloves", "bandages"],
  martialart_shoes: ["martialart_clothes", "boxing_gloves", "bandages"],
  martialart_rubber: ["martialart_exercise", "boxing_gloves", "bandages"],
  martialart_mma: ["boxing_gloves", "bandages", "martialart_mouth_guard", "martialart_protection"],
  martialart_exercise: ["martialart_rubber", "boxing_gloves", "bandages"],

  // Sports
  tennis: ["isotonic", "kneePads", "fitness_gloves", "shoes"],
  padel: ["isotonic", "kneePads", "shoes"],
  mini: ["isotonic", "shoes"],
  badminton: ["isotonic", "kneePads", "shoes"],
  baseball: ["kneePads", "shoes", "isotonic"],
  frisbee: ["isotonic", "shoes", "sunglasses"],
  football: ["kneePads", "isotonic", "shoes", "socks"],
  basketball: ["kneePads", "isotonic", "shoes", "socks"],
  volleyball: ["kneePads", "isotonic", "shoes"],
  rugby: ["kneePads", "isotonic", "shoes"],
  kneePads: ["fitness_gloves", "isotonic", "shoes"],
  isotonic: ["bottle", "shaker", "kneePads"],

  // Fitness
  fitness_gloves: ["kettlebells", "jumprope", "extender", "mats", "shaker"],
  kettlebells: ["fitness_gloves", "mats", "jumprope", "extender", "shaker"],
  accessories_fitnes: ["mats", "fitness_gloves", "extender", "elasticbands"],
  shaker: ["isotonic", "kettlebells", "fitness_gloves", "bottle"],
  extender: ["fitness_gloves", "mats", "elasticbands", "kettlebells"],
  jumprope: ["mats", "fitness_gloves", "shaker", "extender"],
  elasticbands: ["mats", "extender", "fitness_gloves", "gymnastic"],
  mats: ["jumprope", "fitness_gloves", "balance_board", "gymnastic", "elasticbands"],
  hoop: ["mats", "fitness_gloves", "jumprope"],
  gymnastic: ["mats", "elasticbands", "balance_board"],
  balance_board: ["mats", "gymnastic", "fitness_gloves"],

  // Swimming / SUP
  supboard: ["oar", "vest", "sup_accessories", "fin", "hat_sea"],
  oar: ["supboard", "vest", "sup_accessories"],
  fin: ["mask", "goggles", "hat_sea", "vest"],
  vest: ["supboard", "oar", "sup_accessories"],
  sup_accessories: ["supboard", "oar", "vest"],
  mask: ["goggles", "fin", "hat_sea"],
  goggles: ["mask", "fin", "hat_sea"],
  hat_sea: ["mask", "goggles", "vest"],

  // Alpine / Ski
  snowboardsky: ["snowboardsky_boots", "fasteners_sky", "helmet_sky", "skigoggles", "gloves_sky", "bag_sky"],
  snowboardsky_boots: ["socks_sky", "snowboardsky", "gloves_sky", "fasteners_sky"],
  fasteners_sky: ["snowboardsky", "snowboardsky_boots", "sky_care", "bag_sky"],
  closes_ski: ["thermalUnderwear", "gloves_sky", "socks_sky", "buff", "helmet_sky"],
  helmet_sky: ["skigoggles", "gloves_sky", "buff", "snowboardsky", "closes_ski"],
  skigoggles: ["helmet_sky", "buff", "gloves_sky", "sunscreen"],
  sky_care: ["snowboardsky", "fasteners_sky", "bag_sky"],
  air_sky: ["closes_ski", "thermalUnderwear", "buff"],
  gloves_sky: ["helmet_sky", "skigoggles", "socks_sky", "buff"],
  socks_sky: ["snowboardsky_boots", "gloves_sky", "thermalUnderwear"],
  snowshoes: ["trekkingsticks", "gloves_sky", "thermalUnderwear", "socks_sky"],
  bag_sky: ["snowboardsky", "snowboardsky_boots", "sky_care"],
  winter_chains: ["sky_care", "bag_sky"],
  sunscreen: ["skigoggles", "buff", "sunglasses"],
};
